### ISSUE TITLE
C# conversion

### ISSUE THREAD

**Issue by thisTwo** [ajaxvs/poeNullParticles#1]
Hi, and thank you for this small and efficient tool :)
Can you convert this into c# language ...i want it to add it on a tool  that is written in c#.

Thank you,

**Comment by ajaxvs** [comment]
Sorry, I haven't used C# in a long time and have no plans to use it anymore so I think it's not the best idea.

**Comment by thisTwo** [comment]
I just wanted to integrate this tool into this one somehow : https://github.com/vmv/PoeSmoother/releases/tag/v.0.4.
Anyway, thank you for your fast response.

**Comment by thisTwo** [comment]
Just a question...can you add a function to take care of  .aoc files, something like notepad++ has : with find a word, bookmark lines with the searched word, then remove those lines.
Would be an automated removal for audio lines and more.

```
SoundEvents
{
    animation = "idle"
        0 = "Audio/Sound Effects/Pet/Basilisk/Idle_$(#).ogg%05@0.1 115 0 0 0 0 -1 0 1 1"
}
```

Search for this : Audio/Sound...then remove that line.

Thank you.

**Comment by ajaxvs** [comment]
As far as I know .aoc files have no config lines for particles. There're 
some info about models, animations and other resources. Not particles 
that cause 99% of PoE problems.
So it can't be part of this program obviously.

PoeSmoother seems like a good project but I have doubts if these methods 
work fine.
I did something like that (setting particles & emitter durations to "0" 
inside {} script blocks) before. It worked very well for PoE 1.3, but 
after v2.0 release I got heavy performance drops. Other app users 
approved it.
So I decided it's not enough. Seems like we have to remove all script 
lines from config files now (see original wavetop.pet file for example) 
for getting the best performance like I did in this project.
Not sure tho, feel free to try what you want. Good luck with it.

**Comment by thisTwo** [comment]
I did some tests before tuning down the ground effects, and with your solution they will just disappear completely :)...
I know it's great for really toaster computers but if i want to keep some of visual effects just to have an animation there, 0 can't be used.
So, like i said, i did test ground effects with removing just some function from inside .pet, like smokes,mists,distortions...etc (not only revalued emitter/duration - completely removed).....until that ground effect didn't cause any fps drop. This is how i did them. Took me a lot of time but it's working fine. At least for me.. :D

For the .aoc files, there are a lot of other things inside that, like the base structure of the skill, for example if you want discharge to have 0 effects, you need to remove what's inside the SkinMesh..and the structure of the skill where other effects are applied...is removed.
I was thinking that your tool is the best to use to remove/rewrite mass lines...that's why i asked.
And not only the particles are at foul in this game as i see it,...the sounds are a problem to...50++ sounds are used instantly when you hit a big pack of mobs...but this is another story.

I'm not a skilled programmer to begin with, and it's hard for me to implement anything further :).
