### ISSUE TITLE
Патреон подписался 5 дней назад,подпикса пропала и патч вышел

### ISSUE THREAD

**Issue by heavycrusier** [ajaxvs/poeNullParticles#10]
Патреон подписался 5 дней назад,подпикса пропала и патч вышел,не знал как система патреона работает и в самом конце месяца подписался... Можешь,пожалуйста ссылку дать на приватную версию? Тока привыкнуть успел и опять платить через 5 дней что ли?
Был бы очень признателен

**Comment by ajaxvs** [comment]
Not a bug.

Patreon system charges once per month.
You could read this info before & during registration: https://i.imgur.com/oE79AKe.png
It's been told on my main Patreon page as well: https://i.imgur.com/roRVz9K.png
Please be more careful next time if you really want to subscribe for the certain period of time.
