### ISSUE TITLE
NullEffectingAuras

### ISSUE THREAD

**Issue by ArenaMMORPG** [ajaxvs/poeNullParticles#11]
Can you tell me, if there is a way to null all auras? tried different 'buttons' but nothing, maybe im blind

**Comment by ajaxvs** [comment]
Visible auras are some kind of "must-have" features for any gameplay so there's no separate button for them.
Well, if you really want to disable their rendering, you can click Right Mouse Button on the "Null .epk" option, delete or comment "aura" line, Save, Apply.

**Comment by ArenaMMORPG** [comment]
Thank you, it helped. But can you tell me, is there an any way to null Harbinger from Torrent reclamation belt ?

**Comment by ajaxvs** [comment]
I can't test it but you can try to add "harbingerminion" rule for "Advanced -> Null-skin-mesh-based effects".
