### ISSUE TITLE
There is no content.ggpk on steam version

### ISSUE THREAD

**Issue by Ultra-Smork** [ajaxvs/poeNullParticles#12]
I tried to check out all folders that connected with the game, but still didn't notice this file

**Comment by ajaxvs** [comment]
It's ok. There're two international versions of the game:
1. Standalone. It contains "Content.ggpk" file.
2. Steam. It doesn't contain "Content.ggpk".

So the app tries to find .ggpk file first. If it's not found, it automatically switches to the Steam mode.
