### ISSUE TITLE
seismic and exsanguinate mtx

### ISSUE THREAD

**Issue by YaProstoUmniy** [ajaxvs/poeNullParticles#13]
how should i turn on visibility of seismic and exsanguinate(transcendence) mtx's?

**Comment by ajaxvs** [comment]
1. Find developers name of effect you want to keep visible.
2. Add that name as Exception rule.
3. "Apply" modifications again.

For example, "seismic trap" has "subterranean" name, "transcendence" MTX should be "transcendence". Try to add them:
```
subterranean
transcendence
seismic
```
to the "Null particles -> use Except list". You can follow "Menu -> Read Guide" ( https://ajaxvs.eu.org/?t=poenulleffects_private_guide )

and
```
!transcendence
!seismic
```
to the "Null MTX" option in case if you enabled it.

**Comment by YaProstoUmniy** [comment]
tytyty
