### ISSUE TITLE
[Question] Does this also remove microtransactions?

### ISSUE THREAD

**Issue by SakhG** [ajaxvs/poeNullParticles#2]
If not, do you ever plan to add this functionality?

Side question: what's emitter?

**Comment by ajaxvs** [comment]
MTX particle effects - yes, it does by default.
MTX models - no, never. I don't recommend to remove MTX model files at all, because MTX selling is the main GGG profit income. If we'll start to edit MTX models, they'll start to ban us.

Emitters are particles source systems.

**Comment by SakhG** [comment]
So what's the difference between having one or zero emitters?
The amount of particles produced?

**Comment by ajaxvs** [comment]
Exactly. 
Every effect has at least one visible part in "one-emitter" mode - more visibility, less fps. 
"Zero-emitters" mode is supposed to disable all particle sources - less visibility, more fps.
