### ISSUE TITLE
[Question] How to add to exceptions?

### ISSUE THREAD

**Issue by 0ldi** [ajaxvs/poeNullParticles#3]
(I will add, if you do not mind.)
-Legion Icons(loot) on rares.

**Comment by ajaxvs** [comment]
I think it's already added,
https://github.com/ajaxvs/poeNullParticles/blob/master/poeNullEffects/bin/data/DisableAllExceptList.txt
\League_Legion\RewardSystem\

Legion icons were visible the last time I checked.

**Comment by 0ldi** [comment]
probably you should add this to Latest release 
(I have default settings)
![image](https://user-images.githubusercontent.com/16578229/80047079-1d43a000-8515-11ea-94be-82451bd8234e.png)

![image](https://user-images.githubusercontent.com/16578229/80047084-22085400-8515-11ea-8d70-ce8cd347238a.png)

**Comment by 0ldi** [comment]
Ok i download "Latest commit a35b22e on 13 Mar"
and now its looks like this:
![image](https://user-images.githubusercontent.com/16578229/80047992-8b896200-8517-11ea-992d-82be3556ead5.png)



I hope I will see the effects of Sirus? or do you need to add something else?

**Comment by ajaxvs** [comment]
Well, different users would like to have different configuration.
I didn't test Sirius fight at all but other people said 
"\atlasexiles\Orion" should work fine.
Feel free to do any experiments based on your own preferences.
