### ISSUE TITLE
Cyclone effect disappeared.

### ISSUE THREAD

**Issue by strutovsky** [ajaxvs/poeNullParticles#5]
I should say that GGG released new update yesterday (3.11.1b). Have successfully updated, I pushed "Make Good" (I read that need to do that every time when game has been updated). After that, my Cyclone effect disappeared.
P.S. Before update cyclone effect was displayed. 

What i did:
1) Downloaded the latest v200709.
2) Pushed "Make Good" button
3) Loaded backup, then tried again 
4) Tried "Null particles" button only

Steam/Client version works same

"Disable all except list" looks like:
```
\lightning_orb\orb\
\electrical_surge\
\surge\lightning\
Dark_Ritual
Soulrend
FrostFury
Conduit_Sigil
particles\arc\
particles\arc_
\atlasofworldsbosses\chimera\
\smoke_blind_chimera\
\league_betrayal\totem\
\league_betrayal\bosscatarina\
\catarina
\League_Legion\RewardSystem\
\atlasexiles\Orion
//affliction
//delirium
//harvest
//edit lists as you want.

//here i tried many times with many paths
cyclone
cyclone_aoe
metadata\effects\spells\cyclone\cyclone.ao
metadata\effects\spells\cyclone\cyclone.aoc
metadata\effects\spells\cyclone\cyclone_aoe.ao
metadata\effects\spells\cyclone\cyclone_aoe.aoc
metadata\effects\spells\cyclone\enemy_hit.ao
metadata\effects\spells\cyclone\enemy_hit.aoc
metadata\effects\spells\cyclone\
\effects\spells\cyclone\
\effects\spells\cyclone\cyclone_aoe
metadata\effects\spells\cyclone\cyclone
metadata\effects\spells\cyclone\cyclone_aoe
metadata\effects\spells\cyclone\enemy_hit
```

"Disable only list" looks like:
```
\extra_blood\
\corpseexplosion\
\death_particles\
\shatter\
rain
discharge
ground_slam
ice_trap
lightning_arrow
dancing_daggers
rain_of_blades
metadata\particles\cluster_burst\
metadata\particles\wand\
\siphon\
\soul_siphon\
\particles\upheaval
\ground_effects\fire\
\ground_effects\ice\
\ground_effects\lava\
\ground_effects\vaal_cloud\
```

Have no idea, please help me. 😢

**Comment by ajaxvs** [comment]
Just checked, have no issues with cyclone.

1. Are you sure you've added "cyclone" line into the "Except" list before pressing "Make Good" in the new version? (btw the app doesn't work with .ao/.aoc files. So just "cyclone" line should work fine)
2. Are you sure your selected "Make Good" rule isn't # 1 ("Disable All")?
3. The app saves original files into the "backup" folder, are you sure you've unzipped the new app version into the folder with original backup (it should have 20k+ files)?
4. There's the "check list" with "find skill" feature. You can input "cyclone" as filter and check if everything is ok. If there're some numbers >= 1, your skill should be visible. 

For example, there's a 
>\cyclone\

line in my Except list: https://i.imgur.com/eROWlnO.jpg
and my Cyclone is clearly visible.

**Comment by strutovsky** [comment]
Thanks a lot! The problem was in "Make Good" rule (I always chose #1).
