### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FanReol** [ajaxvs/poeNullParticles#6]
the program crashes at 100% after update 3.11 b.

**Comment by ajaxvs** [comment]
This program works 100% as for me.

Can you please provide any details about your crashes?
1. What version do you use? (first line in "Say Thanks" window, e.g. "v. 200709")
2. What "Make Good" rule do you select?
3. Did you use poe-modding-tool or other similar apps?
4. When do the crashes occur?

**Comment by FanReol** [comment]
1.v 200709
2.noDeadBodies, noShadows,but its dont work.
3.no
4.after that the program closes
![image](https://user-images.githubusercontent.com/68178250/87244310-ed85a380-c444-11ea-9228-f6e655aa343d.png)

**Comment by FanReol** [comment]
1.v.200709
2.noDeadBodies,noShadows,but its dont work
3.no
4.after that the program closes
![image](https://user-images.githubusercontent.com/68178250/87244438-09d61000-c446-11ea-97aa-5ea49f900596.png)

**Comment by FanReol** [comment]
после 100% программа закрывается грубо говоря.

**Comment by ajaxvs** [comment]
Well, there's no built-in function to close the app even if theoretical 
errors happen.
Is there any error message? Maybe it's some kind of "out of memory" (the 
app requires ~500 mb free RAM), not sure.

Anyway 3.11.1b patch didn't change .ggpk struct, everything should be 
fine as before.

**Comment by FanReol** [comment]
no error messages,just crashes the program

**Comment by ajaxvs** [comment]
So it's not an app crash, got it. 

You have no app error logs or messages, no Windows error message boxes, no "appcrash" reports. The app was working fine until 3.11.1b patch that changed nothing important and now something forces to close it during runtime.

Ok, I'll keep this issue in my mind, but I'm afraid I can't help you to fix it. I'd recommend to check your system and find out what has been changed after 3.11.1b patch.

**Comment by ajaxvs** [comment]
>I fixed the program

good to hear it
