### ISSUE TITLE
ban

### ISSUE THREAD

**Issue by FanReol** [ajaxvs/poeNullParticles#7]
nice ban for poenulleffects
![image](https://user-images.githubusercontent.com/68178250/87541520-09d64a00-c6aa-11ea-862d-ee77ad28fc0c.png)

**Comment by FanReol** [comment]
I fixed the program, reinstalled the game, used it for a day, and then got banned.

**Comment by ajaxvs** [comment]
And what else did you use on this account? Baoli, Exiled-bot?

**Comment by FanReol** [comment]
only poenulleffects.

**Comment by FanReol** [comment]
I don't use bots

**Comment by vadash** [comment]
How about RMT or using poehud or flask macros ? I cant imagine someone using mod tool and not using something else

**Comment by FanReol** [comment]
I have not such a straight strong PC, the fps is normal in PoE, but I used this prog that the fps was even more, and less friezes, everything.And about hud I knew, but i check on forums that for him get ban faster, Yes and me suits the usual,and about macro on potions I learned only now, when you wrote about them

**Comment by ajaxvs** [comment]
It's pretty clear you've used some "special" software too. No one ever has been banned for poeNullEffects. Yet.

Don't get me wrong. It's possible GGG will start banning users for .ggpk modifications some day. But in that case we'd know about it. Like every user, thousands warnings or bans. Ok, lets wait a bit more. Maybe you're the first one and we'll get bans soon as well. Or maybe aliens will attack our Earth, the same odds.

**Comment by FanReol** [comment]
If I was banned for riot vanguard, although it is not implemented in PoE at all,then I do not know

**Comment by FanReol** [comment]
И до этого включал awakening poe trade,но он просто был включен,я его не юзал

**Comment by FanReol** [comment]
And before that, I turned on awakening poe trade,but it was just turned on,I didn't use it

**Comment by FanReol** [comment]
GGG doesn't tell me what program I was banned for,because of the conditions.

**Comment by FanReol** [comment]
perhaps they gave me a ban for downloading the game, and immediately changed the .ggpk file.

**Comment by ajaxvs** [comment]
Nope.
Not a single ban. No one ever has been banned for .ggpk modifications yet.

Please don't spread false rumors and don't use cheats.
