### ISSUE TITLE
Hi, do u know how to edit the bin files in the ggpk?

### ISSUE THREAD

**Issue by zerger3** [ajaxvs/poeNullParticles#9]

**Comment by ajaxvs** [comment]
Yes.
The public version demonstrates it. When you press "Apply", the app edits some .bin files, feel free to check it.

**Comment by zerger3** [comment]
Hmm when i use the tool "visualggpk" to browse the content.ggpk i dont see a "apply" button.

**Comment by ajaxvs** [comment]
poeNullEffects has nothing to do with VisualGGPK tool.
Please read release notes to known what is the poeNullEffects: https://github.com/ajaxvs/poeNullParticles/releases

I'm not sure what are you trying to do anyway. What is the issue we discuss here?
